categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bugsnag'
  - title: 'リリース時動作確認不要'
    labels:
      - 'リリース時動作確認不要'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  [Comparing Changes](https://github.com/monoqlock/git-learning/compare/$PREVIOUS_TAG...HEAD)
  ## Changes

  $CHANGES

  <!-- 定型作業以外のリリース作業が発生する場合はリンクを追加
  ## リリース手順
  -->
