name: Weekly Metrics

on:
  push:

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("-----start");
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(releases.data);
            const filteredRelease = releases
              .data
              .filter(release => !release.draft && !release.prerelease)
              .map(release => release.tag_name);
            console.log("-----filteredRelease");
            console.log(filteredRelease);
            console.log("-----end");


