name: Create release

on:
  pull_request:
    branches: [ master ]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set selected color
        run: echo '::set-env name=release_tag_name::green'
      - name: Get color
        run: echo 'The selected color is' $release_tag_name
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_tag_name }}
          release_name: $(TZ=UTC date '+%Y%m%d_%H%M')
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false