name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag name to env
        run: echo "RELEASE_TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check
        run: echo RELEASE_TAG_NAME="${{ env.RELEASE_TAG_NAME }}"

      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Create changelog
        run: |
          gem install github_changelog_generator
          github_changelog_generator --user monoqlock --project git-learning --unreleased-only  \
            --token ${{ secrets.GITHUB_TOKEN }} --output ./CHANGELOG.md

      - name: Check md
        run: cat ./CHANGELOG.md

#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.RELEASE_TAG_NAME }}
#          release_name: ${{ env.RELEASE_TAG_NAME }}
#          body_path: ./CHANGELOG.md
#          draft: false
#          prerelease: false
