name: Uptate release draft

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  release-drafter:
    runs-on: ubuntu-latest

    steps:
      - name: Set release name to env
        run: |
          echo "RELEASE_NAME=$(TZ=UTC date '+%Y%m%d_%H%M')" >> $GITHUB_ENV
          echo ${GITHUB_SHA}

      - name: Update draft release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_NAME }}
          commitish: 7515c4d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
