name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set previous tag to env
        env:
          LAST_COMMIT: $(git rev-list --tags --skip=1 --max-count=1)
        run: echo "PREVIOUS_TAG=$(git describe --abbrev=0 --tags $LAST_COMMIT" >> $GITHUB_ENV

      - name: Set release tag to env
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Create changelog
        run: |
          go get github.com/Songmu/ghch/cmd/ghch
          ghch --token=${{ secrets.GITHUB_TOKEN }} --from=${{ env.PREVIOUS_TAG }} --to=${{ env.RELEASE_TAG }}\
            --next-version=${{ env.RELEASE_TAG }} --format=markdown > ./CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "./CHANGELOG.md"
          commit: master
          tag: ${{ env.RELEASE_TAG }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
