name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Set release tag to env
        run: echo "RELEASE_TAG==${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install go
        uses: actions/actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Create changelog
        run: |
          go get github.com/Songmu/ghch/cmd/ghch
          ghch -r cmp-server --token=${{ secrets.GITHUB_TOKEN }} --from=${{ steps.previoustag.outputs.tag }} \
            --next-version=${{ env.RELEASE_TAG }} --format=markdown > ./CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "./CHANGELOG.md"
          commit: master
          tag: ${{ env.RELEASE_TAG }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
