name: Create release

on:
  pull_request:
    branches: master

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag name to env
        run: echo "::set-env name=release_tag_name::$(TZ=UTC date '+%Y%m%d_%H%M')"

      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Create changelog
        run: |
          gem install github_changelog_generator
          github_changelog_generator -u monoqlock -p git-learning --unreleased-only --future-release ${{ env.release_tag_name }} --token ${{ secrets.GITHUB_TOKEN }} -o ./CHANGELOG.md
        id: Changelog

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_tag_name }}
          release_name: ${{ env.release_tag_name }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false