name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag name to env
        run: echo "RELEASE_TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check
        run: echo RELEASE_TAG_NAME="${{ env.RELEASE_TAG_NAME }}"

      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Create changelog
        run: |
          gem install github_changelog_generator
          github_changelog_generator --user monoqlock --project git-learning --max-issues 2 --unreleased-only \
            --token ${{ secrets.GITHUB_TOKEN }} --release-branch master --output ./CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "./CHANGELOG.md"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
