# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Set tag name to env
      run: echo "::set-env name=release_tag_name::$(TZ=UTC date '+%Y%m%d_%H%M')"

    - name: Install ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Create changelog
      id: Changelog
      run: |
        gem install github_changelog_generator
        github_changelog_generator -u monoqlock -p git-learning --unreleased-only --future-release ${{ env.release_tag_name }} --token ${{ secrets.GITHUB_TOKEN }} -o ./CHANGELOG.md
#        echo "::set-output name=note::$()"

    - name: test output
      run: cat ./CHANGELOG.md
