name: Test migration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate-migration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Flyway validate
      run:
        docker run --rm -v ${PWD}/sql:/flyway/sql flyway/flyway -url=jdbc:h2:mem:test -user=sa validate -ignorePendingMigrations=true -validateMigrationNaming=true