name: Update Version

on:
  push:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make changes to pull request
        run: date +%s > date.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update version'
          branch: update-version-"$(TZ=UTC date '+%s')"
          base: master
          commit-message: Update version
          committer: GitHub <noreply@github.com>
          reviewers: ${{ github.actor }}
          labels: リリース時動作確認不要
