name: Weekly Metrics

on:
  push:
    branches: [ master ]

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get tag count
        env:
          start_date: $(date "+%Y%m%d" -d '1 week ago')
          end_date: $(date "+%Y%m%d" -d '1 days ago')
        run: |
          echo Hello
          git fetch
          echo $start_date
          echo $end_date
          git tag --sort=-taggerdate --format '%(taggerdate:format:%Y%m%d)' | awk '$1<=$end_date && $1>=$start_date'
          git tag --sort=-taggerdate --format '%(taggerdate:format:%Y%m%d)' | awk '$1<=20200406 && $1>=20200119' | wc -l
