name: Weekly Metrics

on:
  push:
    branches: [ develop ]

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get tag count
        env:
          start_date: $(date "+%Y%m%d" -d '1 week ago')
          end_date: $(date "+%Y%m%d" -d '1 days ago')
        run: |
          echo Hello
          git fetch
          echo $start_date
          echo $end_date