name: Weekly Metrics

on:
  push:

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag count
      run: |
        echo Hello
        git fetch
        echo $(date "+%Y%m%d" -d '1 week ago')
        echo $(date "+%Y%m%d" -d '1 days ago')
        git tag --sort=-taggerdate --format '%(taggerdate:format:%Y%m%d)' | awk '$1<=$(date "+%Y%m%d" -d \'1 days ago\') && $1>=$(date "+%Y%m%d" -d \'1 week ago\')'
        git tag --sort=-taggerdate --format '%(taggerdate:format:%Y%m%d)' | awk '$1<=20200406 && $1>=20200119' | wc -l
